workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi-with-code-samples:
        inputs:
            - location: registry.speakeasyapi.dev/novu/novu/json-development:main
        overlays:
            - location: registry.speakeasyapi.dev/novu/novu/code-samples-typescript:main
        output: ./openapi.json
        registry:
            location: registry.speakeasyapi.dev/novu/novu/openapi-with-code-samples
targets: {}
